apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-new
  namespace: backup-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc-retain # defined in csi-storageclass.yaml
