/*
Copyright 2022 The SODA Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/soda-cdm/kahu/apis/kahu/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// SnapshotLister helps list Snapshots.
// All objects returned here must be treated as read-only.
type SnapshotLister interface {
	// List lists all Snapshots in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.Snapshot, err error)
	// Get retrieves the Snapshot from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.Snapshot, error)
	SnapshotListerExpansion
}

// snapshotLister implements the SnapshotLister interface.
type snapshotLister struct {
	indexer cache.Indexer
}

// NewSnapshotLister returns a new SnapshotLister.
func NewSnapshotLister(indexer cache.Indexer) SnapshotLister {
	return &snapshotLister{indexer: indexer}
}

// List lists all Snapshots in the indexer.
func (s *snapshotLister) List(selector labels.Selector) (ret []*v1beta1.Snapshot, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1beta1.Snapshot))
	})
	return ret, err
}

// Get retrieves the Snapshot from the index for a given name.
func (s *snapshotLister) Get(name string) (*v1beta1.Snapshot, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1beta1.Resource("snapshot"), name)
	}
	return obj.(*v1beta1.Snapshot), nil
}
