{{ if (.Values.volumeBackupProviders).openEbsZfs.enableProvider }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kahu-openebs-zfs-provider
  namespace: {{ (.Values.global).namespace | default "kahu" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    provisioner: kahu
  name: kahu-openebs-zfs-provider-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kahu-openebs-zfs-provider-clusterrole
subjects:
  - kind: ServiceAccount
    name: kahu-openebs-zfs-provider
    namespace: {{ (.Values.global).namespace | default "kahu" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    provisioner: kahu
  name: kahu-openebs-zfs-provider-clusterrole
rules:
  - apiGroups: ["kahu.io"]
    resources: ["providers", "providers/status"]
    verbs: ["create", "delete", "watch", "update", "patch", "get", "watch", "list"]
  - apiGroups: [ "*" ]
    resources: ["*"]
    verbs: ["create", "delete", "watch", "update", "patch", "get", "watch", "list"]
---
{{ end }}